### ISSUE TITLE
Example with controller and view

### ISSUE THREAD

**Issue by kiwo12345** [ljsystem/bankid#6]
Hello, do you have a full example using this package with a controller and view?
thanks

**Comment by kigh143** [comment]
Hello, were  you able to integrate it. I am trying to implement the same feature in codeiginter.

**Comment by kiwo12345** [comment]
> Hello, were you able to integrate it. I am trying to implement the same feature in codeiginter.

Hi, no im not :(

**Comment by perifer** [comment]
Sorry, but the  current README is all there is at the moment in terms of documentation. I think it’s a good idea to have a basic understanding of the flow by reading the official BankId documentation. But I agree that our documentation could definitely be improved.
