### ISSUE TITLE
No exception being thrown?

### ISSUE THREAD

**Issue by kiwo12345** [ljsystem/bankid#7]
I tried a simple:

```
try {
            $bankId = new BankID();
            $test = $bankId->sign('123123123', $ip);
        } catch (\Exception $e) {
            Log::error($e);
            dd($e);
        }
```

I sent the wrong parameters to the `sign` method but why is no exception being thrown?

**Comment by perifer** [comment]
Generally no exceptions are thrown, instead a BankIDResponse is returned. Look at https://github.com/ljsystem/bankid/blob/94536d6b375dd3a61a5e2fcdce496adaaf6c2f43/src/BankID.php#L185
